CayoFnc = {} 
Cayo = {}
Cayo.CurrentPedList = {}
Cayo.CurrentEntities = {}

Cayo.PedModelList = {
	"s_m_y_clown_01",
	"mp_m_bogdangoon",
	"mp_m_avongoon",
	"s_m_y_xmech_02_mp",
	"mp_m_weapwork_01",
	"mp_m_weapexp_01",
	"mp_m_cocaine_01",
	"a_m_o_tramp_01",
	"u_m_y_mani"
}

Cayo.CreatedPedWeaponList = {
	GetHashKey("WEAPON_ASSAULTRIFLE_MK2"), 
	GetHashKey("WEAPON_MINISMG"), 
	GetHashKey("WEAPON_HEAVYSNIPER_MK2"), 
	GetHashKey("WEAPON_HOMINGLAUNCHER"),
	GetHashKey("WEAPON_COMBATMG_MK2"),
	GetHashKey("WEAPON_RPG")
}

Cayo.PedTowerCoords = {
	{pedId = 0, coords = vector3(5155.2573242188, -4935.533203125, 30.873405456543), heading = 224.30587768554688, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5209.3754882813, -5003.9052734375, 21.562211990356), heading = 125.10303497314, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5145.8178710938, -5050.6098632813, 20.391565322876), heading = 49.746597290039, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5145.8017578125, -5055.98046875, 20.391565322876), heading = 182.26316833496, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5040.8310546875, -5117.5024414063, 22.94460105896), heading = 126.19940185547, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(4901.1127929688, -5339.9638671875, 35.655246734619), heading = 147.41787719727, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(4904.2866210938, -5332.6762695313, 35.655982971191), heading = 359.43521118164, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(4885.0043945313, -5457.8286132813, 47.523777008057), heading = 93.832046508789, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(4890.2592773438, -5457.9755859375, 47.523777008057), heading = 279.13479614258, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(4887.9189453125, -5459.92578125, 47.523777008057), heading = 182.92164611816, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5127.6040039063, -5525.3901367188, 70.970413208008), heading = 304.82693481445, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5126.1279296875, -5528.8173828125, 70.970413208008), heading = 218.83901977539, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5267.2729492188, -5430.37109375, 141.08569335938), heading = 228.57989501953, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5267.201171875, -5425.6811523438, 141.04718017578), heading = 341.04000854492, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5262.76171875, -5428.5825195313, 141.04818725586), heading = 96.563163757324, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5346.5874023438, -5513.1728515625, 65.514434814453), heading = 215.22364807129, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5362.681640625, -5437.8627929688, 66.176414489746), heading = 240.09936523438, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5357.9638671875, -5438.4770507813, 66.176414489746), heading = 152.7912902832, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5468.0888671875, -5234.572265625, 43.96174621582), heading = 319.81817626953, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5464.9848632813, -5238.9916992188, 43.96174621582), heading = 193.96293640137, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5140.5517578125, -5246.6909179688, 26.291900634766), heading = 182.94316101074, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5143.3681640625, -5241.4965820313, 26.291900634766), heading = 350.88067626953, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(4981.1987304688, -5601.8891601563, 23.828020095825), heading = 326.44119262695, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(4973.6596679688, -5597.2250976563, 23.675422668457), heading = 325.48794555664, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 100.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5019.3500976563, -5746.9008789063, 32.852725982666), heading = 320.52844238281, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 150.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5011.2802734375, -5742.1557617188, 32.852802276611), heading = 9.7120704650879, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 150.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5001.5166015625, -5753.5185546875, 32.852722167969), heading = 115.34055328369, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 150.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(5011.5400390625, -5759.8090820313, 32.852722167969), heading = 200.03352355957, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 150.0, maxVehDst = 1000.0},
	{pedId = 0, coords = vector3(4905.1669921875, -5832.9892578125, 28.215908050537), heading = 359.953125, weapons = {{"WEAPON_ASSAULTRIFLE_MK2"}}, maxDst = 150.0, maxVehDst = 1000.0},
}

Cayo.Utils = {
	islandCenter = vector3(4988.7192382813, -4992.6948242188, 25.246885299683),
	pedCoords = vector3(0, 0, 0),
	ped = 0,
	lastSet = "",
	defaultIpl = 'outOfRange',
	massiveLoad = false,
	forceMap = true,
	useMines = false,
	mineThreadActive = false,
	inCamp = false,
	allowedInCamp = false,
	timerBetweenSpawns = 1000 * 20,
	maxPed = 12
}

Cayo.Zones = {
	{
		coords = vector3(5143.248046875, -4955.0161132813, 14.361158370972),
		maxDst = 3.0,
		name = "CayoPericoAuthCheck",
		protectEvents = true,
		isPed = true,
		isZone = true,
		nuiLabel = "Montrer votre invitation",
		pedInfo = {
			coords = vector3(5143.248046875, -4955.0161132813, 14.361158370972),
			heading = 320.1147766113281,
			model = 'mp_m_weapexp_01', 
			scenario = 'WORLD_HUMAN_COP_IDLES',
			pedId = 0,
		}
	},

	{
		coords = vector3(4825.8344726563, -5172.0932617188, 2.1756789684296),
		maxDst = 3.0,
		name = "CayoPericoAuthCheck2",
		protectEvents = true,
		isPed = true,
		isZone = true,
		nuiLabel = "Montrer votre invitation",
		pedInfo = {
			coords = vector3(4825.8344726563, -5172.0932617188, 2.1756789684296),
			heading = 84.97032928466797,
			model = 'mp_m_weapexp_01', 
			scenario = 'WORLD_HUMAN_COP_IDLES',
			pedId = 0,
		}
	},

	{
		coords = vector3(4988.7192382813, -4992.6948242188, 25.246885299683),
		maxDst = 1500.0,
		name = "CayoPerico",
		isZone = true,
		protectEvents = true,
		zoneMap = {
			shouldTriggerEvent = true,
			inEvent = "InCayoPerico",
			outEvent = "OutOfCayoPerico"
		}
	},

	{
		coords = vector3(5217.63671875, -5636.3642578125, 37.520652770996),
		maxDst = 600.0,
		name = "CayoPericoCamp",
		isZone = true,
		protectEvents = true,
		zoneMap = {
			shouldTriggerEvent = true,
			inEvent = "InCayoPericoCamp",
			outEvent = "OutOfCayoPericoCamp"
		}
	},

	{
		coords = vector3(4988.7192382813, -4992.6948242188, 25.246885299683),
		maxDst = 1500.0,
		name = "CayoPericoInZone",
		isZone = true,
		protectEvents = true,
		zoneMap = {
			shouldTriggerEvent = true,
			inEvent = "CayoPericoInZone",
			outEvent = "CayoPericoInMidRange"
		}
	},

	{
		coords = vector3(4988.7192382813, -4992.6948242188, 25.246885299683),
		maxDst = 2500.0,
		name = "CayoPericoInMidRange",
		isZone = true,
		protectEvents = true,
		zoneMap = {
			shouldTriggerEvent = true,
			inEvent = "CayoPericoInMidRange",
			outEvent = "CayoPericoInLongRange"
		}
	},

	{
		coords = vector3(4988.7192382813, -4992.6948242188, 25.246885299683),
		maxDst = 5000.0,
		name = "CayoPericoInLongRange",
		isZone = true,
		protectEvents = true,
		zoneMap = {
			shouldTriggerEvent = true,
			inEvent = "CayoPericoInLongRange",
			outEvent = "CayoPericoOutOfRange"
		}
	}
}

Cayo.EntranceItems = {
	'cayo_invitation'
}

Cayo.EntranceZone = {
	'CayoPericoAuthCheck',
	'CayoPericoAuthCheck2'
}

Cayo.Ipls = {
	inZone = {
		sleepTimer = 1000,
		maxDst = 1500,
		isSet = false,
		fnc = 'SetInZone',
		list = {
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_09"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_06"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_05"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_01"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_00"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_08"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_04"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_07"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_03"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_04"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_05_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_d_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_a_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_c_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_01"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_04"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_06"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_04_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_a"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_a_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_f_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_b"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_b_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_e_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_05_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_a"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_01_long_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_03"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_b_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_01_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_04_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_d_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_f_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_c"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_06_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_c_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_c"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_06_strm_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_05"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_e_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_c_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_03"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_f"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_06_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_01"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_06"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_a_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_b_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_b"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_02_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_e"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_d"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_05"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02_grass_2"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_01_grass_1"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_05_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_01_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02_grass_1"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02_grass_3"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_04_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_06_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_04_grass_1"},
			{fnc = 'RequestIpl', ipl = "island_distantlights"},
			{fnc = 'RequestIpl', ipl = "island_lodlights"},
			{fnc = 'RequestIpl', ipl = "h4_yacht_strm_0"},
			{fnc = 'RequestIpl', ipl = "h4_yacht"},
			{fnc = 'RequestIpl', ipl = "h4_yacht_long_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_clubposter_palmstraxx"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_02_int"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_02"},
			{fnc = 'RequestIpl', ipl = "h4_clubposter_moodymann"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_01"},
			{fnc = 'RequestIpl', ipl = "h4_clubposter_keinemusik"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_03"},
			{fnc = 'RequestIpl', ipl = "h4_ch2_mansion_final"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_03_int"},
			{fnc = 'RequestIpl', ipl = "h4_yacht_critical_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_01_int"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_placement"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_vault"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_checkpoint_props"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_hangar_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_00_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_06_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_00"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_barrack_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_09_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_05"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_se_placement"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_09"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_09"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_mansion_b"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_hangar_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_entrance_fence"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_09"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_09_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_checkpoint"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_water_hatch"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_04_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_props"},
			{fnc = 'RequestIpl', ipl = "h4_beach"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lockup_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_04_slod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_nw_placement"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_08_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_09_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_08_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_03"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_02_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_00"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_b_side_fence"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_06_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_03"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_01"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_07"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_props_2"},
			{fnc = 'RequestIpl', ipl = "h4_islandxtower_veg"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_sw_placement"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_01_slod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_wtowers"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_04"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_airstrip_interior_0_airstrip_hanger"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lockup_01"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_barrack_props"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_07_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_00_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_08_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lockup_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_07_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_doorsclosed_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_04_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_checkpoint_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_04"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_07"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_mansion_b_strm_0"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_09_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_07_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_05_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_08"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_07"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_propsb_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_checkpoint_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_aa_guns_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_06"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_props_2_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_office"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_dock"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_propsb"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lockup_03"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_05_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_05"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_props_2_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_04_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_01"},
			{fnc = 'RequestIpl', ipl = "h4_beach_party_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lights"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_00_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_guardfence"},
			{fnc = 'RequestIpl', ipl = "h4_beach_props_party"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_b"},
			{fnc = 'RequestIpl', ipl = "h4_beach_bar_props"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_04"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_08_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxtower"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_00_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_barrack_hatch"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_06_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_03_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_09_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_02_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_04_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_05_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_08_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_05_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_b_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_08"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_props"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_doorsopen_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_05_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxcanal_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_mansion_gate_closed"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_02_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_02"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_08_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_08"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_05"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_props_2_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_03_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_01_slod"},
			{fnc = 'RequestIpl', ipl = "h4_beach_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_underwater_gate_closed"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_00_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_doorsopen"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_01_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_00"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_06"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lockup_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxtower_veg_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_00"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_04_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_07_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_hangar_props"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_06_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxtower_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_beach_party"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_06_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_doorsclosed"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_00_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_07_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_props_2_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_props"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_09"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_06"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_03"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lockup_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_beach_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_07_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_01"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_office_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_lod"},
			{fnc = 'RequestIpl', ipl = "h4_beach_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_05_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_checkpoint_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_05_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_03_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_05"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_mansion"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_03"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_08_slod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_ne_placement"},
			{fnc = 'RequestIpl', ipl = "h4_aa_guns"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_propsb_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_01"},
			{fnc = 'RequestIpl', ipl = "h4_mansion_remains_cage"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_01_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_06_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_08"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_04_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_04_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_beach"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_06_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_06_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_00_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_07_slod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_mansion_strm_0"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_02_slod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_airstrip"},
			-- {fnc = 'RequestIpl', ipl = "h4_mansion_gate_brok"},
			{fnc = 'RequestIpl', ipl = "h4_island_padlock_props"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_06"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_09_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxcanal_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_05_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_09_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_vault_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_03_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_08_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_barrack_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxtower_veg_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_04"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_props"},
			{fnc = 'RequestIpl', ipl = "h4_islandxtower_slod"},
			{fnc = 'RequestIpl', ipl = "h4_beach_props"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_b_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_07_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_07"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_props_2"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_09_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxcanal_props"},
			{fnc = 'RequestIpl', ipl = "h4_beach_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_00_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_disc_strandedshark"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_disc_strandedshark_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_strm_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_sea_mines"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island"},
			{fnc = 'RequestIpl', ipl = "h4_boatblockers"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_long_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_disc_strandedwhale"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_disc_strandedwhale_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_props"},
			{fnc = 'RequestIpl', ipl = "h4_int_placement_h4_interior_1_dlc_int_02_h4_milo_"},
			{fnc = 'RequestIpl', ipl = "h4_int_placement_h4_interior_0_int_sub_h4_milo_"},
			{fnc = 'RequestIpl', ipl = "h4_int_placement_h4"}
		}
	},
	midRange = {
		sleepTimer = 1000,
		maxDst = 2500,
		isSet = false,
		fnc = 'SetMidRange',
		list = {
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_09"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_06"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_05"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_01"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_00"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_08"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_04"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_07"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_03"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_04"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_05_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_d_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_a_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_c_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_01"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_04"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_06"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_04_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_a"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_a_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_f_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_b"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_b_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_e_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_05_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_a"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_01_long_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_03"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_b_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_01_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_04_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_d_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_f_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_c"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_06_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_c_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_c"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_06_strm_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_05"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_e_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_c_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_03"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_f"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_06_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_01"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_06"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_a_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_b_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_b"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_02_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_e"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_d"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_05"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02_grass_2"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_01_grass_1"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_05_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_01_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02_grass_1"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02_grass_3"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_04_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_06_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_04_grass_1"},
			{fnc = 'RequestIpl', ipl = "island_distantlights"},
			{fnc = 'RequestIpl', ipl = "island_lodlights"},
			{fnc = 'RequestIpl', ipl = "h4_yacht_strm_0"},
			{fnc = 'RequestIpl', ipl = "h4_yacht"},
			{fnc = 'RequestIpl', ipl = "h4_yacht_long_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_clubposter_palmstraxx"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_02_int"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_02"},
			{fnc = 'RequestIpl', ipl = "h4_clubposter_moodymann"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_01"},
			{fnc = 'RequestIpl', ipl = "h4_clubposter_keinemusik"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_03"},
			{fnc = 'RequestIpl', ipl = "h4_ch2_mansion_final"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_03_int"},
			{fnc = 'RequestIpl', ipl = "h4_yacht_critical_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_yacht_01_int"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_placement"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_vault"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_checkpoint_props"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_hangar_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_00_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_06_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_00"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_barrack_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_09_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_05"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_se_placement"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_09"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_09"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_mansion_b"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_hangar_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_entrance_fence"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_09"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_09_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_checkpoint"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_water_hatch"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_04_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_props"},
			{fnc = 'RequestIpl', ipl = "h4_beach"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lockup_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_04_slod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_nw_placement"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_08_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_09_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_08_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_03"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_02_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_00"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_b_side_fence"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_06_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_03"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_01"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_07"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_props_2"},
			{fnc = 'RequestIpl', ipl = "h4_islandxtower_veg"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_sw_placement"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_01_slod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_wtowers"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_04"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_airstrip_interior_0_airstrip_hanger"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lockup_01"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_barrack_props"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_07_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_00_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_08_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lockup_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_07_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_doorsclosed_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_04_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_checkpoint_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_04"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_07"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_mansion_b_strm_0"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_09_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_07_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_05_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_08"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_07"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_propsb_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_checkpoint_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_aa_guns_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_06"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_props_2_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_office"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_dock"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_propsb"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lockup_03"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_05_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_05"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_props_2_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_04_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_01"},
			{fnc = 'RequestIpl', ipl = "h4_beach_party_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lights"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_00_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_guardfence"},
			{fnc = 'RequestIpl', ipl = "h4_beach_props_party"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_b"},
			{fnc = 'RequestIpl', ipl = "h4_beach_bar_props"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_04"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_08_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxtower"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_00_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_barrack_hatch"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_06_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_03_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_09_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_02_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_04_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_05_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_08_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_05_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_b_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_08"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_props"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_doorsopen_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_05_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxcanal_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_mansion_gate_closed"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_02_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_02"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_08_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_08"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_05"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_props_2_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_03_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_01_slod"},
			{fnc = 'RequestIpl', ipl = "h4_beach_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_underwater_gate_closed"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_00_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_doorsopen"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_01_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_00"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_06"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lockup_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxtower_veg_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_00"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_04_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_07_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_hangar_props"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_06_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxtower_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_beach_party"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_06_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_doorsclosed"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_00_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_07_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_props_2_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_props"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_09"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_06"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_03"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_lockup_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_beach_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_07_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_01"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_office_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_lod"},
			{fnc = 'RequestIpl', ipl = "h4_beach_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_05_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_checkpoint_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_05_lod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_03_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_05"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_mansion"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_03"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_08_slod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_ne_placement"},
			{fnc = 'RequestIpl', ipl = "h4_aa_guns"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_propsb_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_01"},
			{fnc = 'RequestIpl', ipl = "h4_mansion_remains_cage"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_01_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_06_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_08"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_04_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_04_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_beach"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_06_lod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_06_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_00_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_07_slod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_mansion_strm_0"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_02_slod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_airstrip"},
			{fnc = 'RequestIpl', ipl = "h4_mansion_gate_brok"},
			{fnc = 'RequestIpl', ipl = "h4_island_padlock_props"},
			{fnc = 'RequestIpl', ipl = "h4_islandairstrip_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_06"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_09_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxcanal_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_05_slod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_09_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_vault_lod"},
			{fnc = 'RequestIpl', ipl = "h4_se_ipl_03_slod"},
			{fnc = 'RequestIpl', ipl = "h4_nw_ipl_08_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_barrack_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxtower_veg_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_04"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_props"},
			{fnc = 'RequestIpl', ipl = "h4_islandxtower_slod"},
			{fnc = 'RequestIpl', ipl = "h4_beach_props"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_mansion_b_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_maindock_props_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_07_slod"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_07"},
			{fnc = 'RequestIpl', ipl = "h4_islandxdock_props_2"},
			{fnc = 'RequestIpl', ipl = "h4_ne_ipl_09_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandxcanal_props"},
			{fnc = 'RequestIpl', ipl = "h4_beach_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_00_slod"},
			{fnc = 'RequestIpl', ipl = "h4_sw_ipl_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_disc_strandedshark"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_disc_strandedshark_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_props_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_strm_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_sea_mines"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island"},
			{fnc = 'RequestIpl', ipl = "h4_boatblockers"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_island_long_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_disc_strandedwhale"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_disc_strandedwhale_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_props"},
			{fnc = 'RequestIpl', ipl = "h4_int_placement_h4_interior_1_dlc_int_02_h4_milo_"},
			{fnc = 'RequestIpl', ipl = "h4_int_placement_h4_interior_0_int_sub_h4_milo_"},
			{fnc = 'RequestIpl', ipl = "h4_int_placement_h4"}
		}
	},
	longrange = {
		sleepTimer = 1000,
		maxDst = 5000,
		isSet = false,
		fnc = 'SetLongRange',
		list = {
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_09"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_06"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_05"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_01"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_00"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_08"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_04"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_07"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_03"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_occ_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_04"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_05_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_d_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_a_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_c_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_01"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_04"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_06"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_04_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_03_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_a"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_a_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_f_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_b"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_b_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_e_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_05_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_a"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_01_long_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_03"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_b_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_01_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_04_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_d_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_f_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_c"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_02_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_06_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_c_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_c"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_01_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_06_strm_0"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_05"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_e_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_c_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_03"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_f"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_06_lod"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_01"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_06"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_a_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_06_b_lod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_b"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_02_slod"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_e"},
			{fnc = 'RequestIpl', ipl = "h4_islandx_terrain_props_05_d"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_05"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02_grass_2"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_01_grass_1"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_05_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_01_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02_grass_1"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_02_grass_3"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_04_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_06_grass_0"},
			{fnc = 'RequestIpl', ipl = "h4_mph4_terrain_04_grass_1"},
			{fnc = 'RemoveIpl', ipl = "island_distantlights"},
			{fnc = 'RemoveIpl', ipl = "island_lodlights"},
			{fnc = 'RemoveIpl', ipl = "h4_yacht_strm_0"},
			{fnc = 'RemoveIpl', ipl = "h4_yacht"},
			{fnc = 'RemoveIpl', ipl = "h4_yacht_long_0"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_clubposter_palmstraxx"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_02_int"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_02"},
			{fnc = 'RemoveIpl', ipl = "h4_clubposter_moodymann"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_01"},
			{fnc = 'RemoveIpl', ipl = "h4_clubposter_keinemusik"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_03"},
			{fnc = 'RemoveIpl', ipl = "h4_ch2_mansion_final"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_03_int"},
			{fnc = 'RemoveIpl', ipl = "h4_yacht_critical_0"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_01_int"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_placement"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_vault"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_checkpoint_props"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_hangar_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_00_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_06_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_00"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_02"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_barrack_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_09_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_05"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_se_placement"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_09"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_09"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_mansion_b"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_hangar_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_entrance_fence"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_09"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_02_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_09_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_02"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_checkpoint"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_water_hatch"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_04_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_props"},
			{fnc = 'RemoveIpl', ipl = "h4_beach"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lockup_03_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_04_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_nw_placement"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_08_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_09_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_08_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_03"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_02_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_00"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_b_side_fence"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_06_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_03"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_01"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_07"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_props_2"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxtower_veg"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_sw_placement"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_01_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_wtowers"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_02_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_04"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_airstrip_interior_0_airstrip_hanger"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lockup_01"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_barrack_props"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_07_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_00_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_08_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lockup_02"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_07_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_doorsclosed_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_02_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_04_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_checkpoint_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_04"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_07"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_mansion_b_strm_0"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_09_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_07_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_05_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_08"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_07"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_propsb_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_checkpoint_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_aa_guns_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_06"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_props_2_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_office"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_dock"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_propsb"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lockup_03"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_05_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_05"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_props_2_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_04_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_01"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_party_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lights"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_00_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_guardfence"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_props_party"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_03_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_b"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_bar_props"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_04"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_08_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxtower"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_00_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_barrack_hatch"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_06_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_03_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_09_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_02_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_04_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_05_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_08_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_05_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_b_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_08"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_props"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_doorsopen_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_05_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxcanal_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_mansion_gate_closed"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_02_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_02"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_08_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_08"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_05"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_02_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_props_2_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_03_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_01_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_underwater_gate_closed"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_00_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_doorsopen"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_01_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_00"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_06"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lockup_02_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxtower_veg_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_00"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_04_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_07_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_hangar_props"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_06_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxtower_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_party"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_06_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_doorsclosed"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_00_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_02"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_07_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_props_2_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_props"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_09"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_06"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_03_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_03"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lockup_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_07_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_01"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_office_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_05_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_checkpoint_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_05_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_03_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_03_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_05"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_mansion"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_03"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_08_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_ne_placement"},
			{fnc = 'RemoveIpl', ipl = "h4_aa_guns"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_propsb_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_01"},
			{fnc = 'RemoveIpl', ipl = "h4_mansion_remains_cage"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_01_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_06_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_08"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_04_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_04_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_beach"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_06_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_06_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_00_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_07_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_mansion_strm_0"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_02_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_airstrip"},
			{fnc = 'RemoveIpl', ipl = "h4_mansion_gate_brok"},
			{fnc = 'RemoveIpl', ipl = "h4_island_padlock_props"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_06"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_09_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxcanal_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_05_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_09_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_vault_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_03_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_08_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_barrack_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxtower_veg_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_04"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_props"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxtower_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_props"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_b_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_07_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_07"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_props_2"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_09_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxcanal_props"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_00_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_03_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_disc_strandedshark"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_disc_strandedshark_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_strm_0"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_sea_mines"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island"},
			{fnc = 'RemoveIpl', ipl = "h4_boatblockers"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_long_0"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_disc_strandedwhale"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_disc_strandedwhale_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_props"},
			{fnc = 'RemoveIpl', ipl = "h4_int_placement_h4_interior_1_dlc_int_02_h4_milo_"},
			{fnc = 'RemoveIpl', ipl = "h4_int_placement_h4_interior_0_int_sub_h4_milo_"},
			{fnc = 'RemoveIpl', ipl = "h4_int_placement_h4"}
		}
	},
	outOfRange = {
		sleepTimer = 5000,
		maxDst = -1,
		isSet = false,
		fnc = 'SetOutOfRange',
		list = {
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_occ_09"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_occ_06"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_occ_05"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_occ_01"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_occ_00"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_occ_08"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_occ_04"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_occ_07"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_occ_03"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_occ_02"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_04"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_05_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_d_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_02"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_a_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_c_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_01"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_04"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_06"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_04_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_03_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_06_a"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_06_a_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_f_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_06_b"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_b_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_e_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_05_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_02"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_a"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_01_long_0"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_03"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_06_b_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_01_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_04_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_d_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_f_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_c"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_02_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_06_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_06_c_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_06_c"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_06_strm_0"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_05"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_e_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_06_c_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_03"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_f"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_06_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_01"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_06"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_06_a_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_06_b_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_b"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_02_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_e"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_terrain_props_05_d"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_05"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_02_grass_2"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_01_grass_1"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_05_grass_0"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_01_grass_0"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_02_grass_1"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_02_grass_0"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_02_grass_3"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_04_grass_0"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_06_grass_0"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_terrain_04_grass_1"},
			{fnc = 'RemoveIpl', ipl = "island_distantlights"},
			{fnc = 'RemoveIpl', ipl = "island_lodlights"},
			{fnc = 'RemoveIpl', ipl = "h4_yacht_strm_0"},
			{fnc = 'RemoveIpl', ipl = "h4_yacht"},
			{fnc = 'RemoveIpl', ipl = "h4_yacht_long_0"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_clubposter_palmstraxx"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_02_int"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_02"},
			{fnc = 'RemoveIpl', ipl = "h4_clubposter_moodymann"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_01"},
			{fnc = 'RemoveIpl', ipl = "h4_clubposter_keinemusik"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_03"},
			{fnc = 'RemoveIpl', ipl = "h4_ch2_mansion_final"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_03_int"},
			{fnc = 'RemoveIpl', ipl = "h4_yacht_critical_0"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_yacht_01_int"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_placement"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_vault"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_checkpoint_props"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_hangar_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_00_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_06_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_00"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_02"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_barrack_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_09_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_05"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_se_placement"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_09"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_09"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_mansion_b"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_hangar_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_entrance_fence"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_09"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_02_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_09_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_02"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_checkpoint"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_water_hatch"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_04_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_props"},
			{fnc = 'RemoveIpl', ipl = "h4_beach"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lockup_03_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_04_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_nw_placement"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_08_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_09_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_08_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_03"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_02_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_00"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_b_side_fence"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_06_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_03"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_01"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_07"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_props_2"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxtower_veg"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_sw_placement"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_01_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_wtowers"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_02_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_04"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_airstrip_interior_0_airstrip_hanger"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lockup_01"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_barrack_props"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_07_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_00_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_08_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lockup_02"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_07_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_doorsclosed_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_02_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_04_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_checkpoint_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_04"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_07"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_mansion_b_strm_0"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_09_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_07_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_05_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_08"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_07"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_propsb_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_checkpoint_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_aa_guns_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_06"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_props_2_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_office"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_dock"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_propsb"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lockup_03"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_05_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_05"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_props_2_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_04_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_01"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_party_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lights"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_00_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_guardfence"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_props_party"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_03_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_b"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_bar_props"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_04"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_08_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxtower"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_00_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_barrack_hatch"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_06_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_03_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_09_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_02_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_04_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_05_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_08_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_05_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_b_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_08"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_props"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_doorsopen_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_05_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxcanal_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_mansion_gate_closed"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_02_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_02"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_08_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_08"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_05"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_02_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_props_2_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_03_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_01_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_underwater_gate_closed"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_00_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_doorsopen"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_01_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_00"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_06"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lockup_02_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxtower_veg_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_00"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_04_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_07_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_hangar_props"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_06_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxtower_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_party"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_06_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_doorsclosed"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_00_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_02"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_07_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_props_2_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_props"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_09"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_06"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_03_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_03"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_lockup_01_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_07_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_01"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_office_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_05_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_checkpoint_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_05_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_03_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_03_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_05"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_mansion"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_03"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_08_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_ne_placement"},
			{fnc = 'RemoveIpl', ipl = "h4_aa_guns"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_propsb_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_01"},
			{fnc = 'RemoveIpl', ipl = "h4_mansion_remains_cage"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_01_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_06_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_08"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_04_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_04_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_beach"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_06_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_06_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_00_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_07_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_mansion_strm_0"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_02_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_airstrip"},
			{fnc = 'RemoveIpl', ipl = "h4_mansion_gate_brok"},
			{fnc = 'RemoveIpl', ipl = "h4_island_padlock_props"},
			{fnc = 'RemoveIpl', ipl = "h4_islandairstrip_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_06"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_09_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxcanal_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_05_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_09_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_vault_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_se_ipl_03_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_nw_ipl_08_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_barrack_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxtower_veg_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_04"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_props"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxtower_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_props"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_mansion_b_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_maindock_props_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_07_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_07"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxdock_props_2"},
			{fnc = 'RemoveIpl', ipl = "h4_ne_ipl_09_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandxcanal_props"},
			{fnc = 'RemoveIpl', ipl = "h4_beach_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_00_slod"},
			{fnc = 'RemoveIpl', ipl = "h4_sw_ipl_03_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_disc_strandedshark"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_disc_strandedshark_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_props_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_strm_0"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_sea_mines"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island"},
			{fnc = 'RemoveIpl', ipl = "h4_boatblockers"},
			{fnc = 'RemoveIpl', ipl = "h4_mph4_island_long_0"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_disc_strandedwhale"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_disc_strandedwhale_lod"},
			{fnc = 'RemoveIpl', ipl = "h4_islandx_props"},
			{fnc = 'RemoveIpl', ipl = "h4_int_placement_h4_interior_1_dlc_int_02_h4_milo_"},
			{fnc = 'RemoveIpl', ipl = "h4_int_placement_h4_interior_0_int_sub_h4_milo_"},
			{fnc = 'RemoveIpl', ipl = "h4_int_placement_h4"}
		}
	}
}